site_name: Missão AGRO
site_url: https://github.com/felixlaryssa/Missao-Agro

repo_url: https://github.com/felixlaryssa/Missao-Agro
repo_name: GitHub

theme:
  name: material
  logo: images/logoUnb.svg   
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/felixlaryssa/Missao-Agro

nav:
  - Apresentação: index.md
  - Atas :
    - Ata 1: Atas/ata1.md
  -  Planejamento : 
      - Ferramentas: Planejamento/Ferramentas.md
      - Metodologia: Planejamento/Metodologia.md
      - Cronograma: Planejamento/Cronograma.md
  -  Atividades Desenvolvidas:
      - AtividadesDesenvolvidas: Atividades.md
  -  Bibliografia:
      - Bibliografia: Bibliografia.md